# fly.toml app configuration file generated for verdearoma-backend on 2025-11-03T20:58:48-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'verdearoma-backend'
primary_region = 'gru'

[build]
  dockerfile = './Dockerfile'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
